### ISSUE TITLE
Error while setting up szep_kartya platform for sensor

### ISSUE THREAD

**Issue by elmerenges** [ofalvai/home-assistant-szep-kartya#12]
Egy ideje nem működik a szenzor.
Ez a hibaüzenet:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/szep_kartya/sensor.py", line 48, in setup_platform
    sensor.update()
  File "/config/custom_components/szep_kartya/sensor.py", line 95, in update
    self.fetch_balance()
  File "/config/custom_components/szep_kartya/sensor.py", line 122, in fetch_balance
    self.balance_vendeglatas = parse_balance(response_json[1]['szamla_osszeg7'])
TypeError: string indices must be integers
```

**Comment by elmerenges** [comment]
Rájöttem, én hibáztam, zárom ezt az issue-t.
