### ISSUE TITLE
Error while setting up platform szep_kartya

### ISSUE THREAD

**Issue by kantorbalazs** [ofalvai/home-assistant-szep-kartya#2]
Sun Jan 19 2020 18:11:16 GMT+0100 (közép-európai téli idő)
Error while setting up platform szep_kartya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/szep_kartya/sensor.py", line 45, in setup_platform
    sensor.update()
  File "/config/custom_components/szep_kartya/sensor.py", line 92, in update
    self.fetch_balance()
  File "/config/custom_components/szep_kartya/sensor.py", line 116, in fetch_balance
    self.balance_vendeglatas = parse_balance(response_json[1]['szamla_osszeg7'])
TypeError: list indices must be integers or slices, not str

Hello! 
Egy pár napja ez a hibaüzenet fogad, ami korábban tökéletesen beolvasta az összegeket.
Tudsz segíteni? :)

Köszi!

**Comment by ofalvai** [comment]
Hello!

Úgy tűnik az OTP honlapján van a hiba, mert ott sem tudom lekérdezni az egyenleget:
![image](https://user-images.githubusercontent.com/1694986/72717877-2d925a80-3b75-11ea-9f8a-5488d4542c75.png)

**Comment by kantorbalazs** [comment]
Melyik oldal ez? 
Nekem itt: magan.szepkartya.otpportalok.hu/egyenleglekerdezes/ Működik

**Comment by ofalvai** [comment]
Kicsit próbálkoztam még, és úgy tűnik bizonyos számú kérést még enged a honlap a captcha megkövetelése nélkül, de utána letilt. Frissítettem a kódot is, érdemes most megpróbálnod.
Plusz javasolom hogy a configban a `scan_interval`-t állítsd be több órásra, és akkor nem frissítgeti túl gyakran (https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval). Nálam 12 órára van állítva, és így stabilan működik napok óta, de szerintem pár óránkénti frissítés is oké még.

**Comment by kantorbalazs** [comment]
Próbáltam várni jópár órát, hogy ne legyen probléma, de továbbra is ez a hiba:
Error while setting up szep_kartya platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 159, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/szep_kartya/sensor.py", line 45, in setup_platform
    sensor.update()
  File "/config/custom_components/szep_kartya/sensor.py", line 92, in update
    self.fetch_balance()
  File "/config/custom_components/szep_kartya/sensor.py", line 116, in fetch_balance
    self.balance_vendeglatas = parse_balance(response_json[1]['szamla_osszeg7'])
TypeError: list indices must be integers or slices, not str

**Comment by pacman789** [comment]
> Kicsit próbálkoztam még, és úgy tűnik bizonyos számú kérést még enged a honlap a captcha megkövetelése nélkül, de utána letilt. Frissítettem a kódot is, érdemes most megpróbálnod.
> Plusz javasolom hogy a configban a `scan_interval`-t állítsd be több órásra, és akkor nem frissítgeti túl gyakran (https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval). Nálam 12 órára van állítva, és így stabilan működik napok óta, de szerintem pár óránkénti frissítés is oké még.

Nálam is jó lett:) 12órás lekérdezéssel. Köszi szépen!
